---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: 
    name:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
    update_cache: yes
    state: latest

- name: Install wanted server packages
  apt:
    name:
        - build-essential
        - vim
        - git
    state: present
